const ERROR_MESSAGE = {
  SESSION: {
    FETCH_FAILED: '세션 정보를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    SET_FAILED: '세션 정보를 설정하는 데 실패했습니다. 다시 시도해주세요.',
  },
  REPORT: {
    REPORT_FAILED: '신고에 실패했습니다. 다시 시도해주세요.',
  },
  AUTH: {
    LOGIN_STATUS_CHECK_FAILED: '로그인 상태를 확인하는 데 실패했습니다. 다시 시도해주세요.',
    LOGOUT_FAILED: '로그아웃에 실패했습니다. 다시 시도해주세요.',
  },
  USER: {
    ID_FETCH_FAILED: '사용자 ID를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    ROLE_FETCH_FAILED: '내 역할을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    INFO_FETCH_FAILED: '사용자 정보를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    SIGN_UP_FAILED: '회원가입에 실패했습니다. 다시 시도해주세요.',
    NICKNAME_DUPLICATE_CHECK_FAILED: '닉네임 중복 확인에 실패했습니다. 다시 시도해주세요.',
    LIST_FETCH_FAILED: '유저 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    PROFILE_VISIBILITY_FETCH_FAILED: '프로필 공개 범위 설정을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    PROFILE_VISIBILITY_UPDATE_FAILED: '프로필 공개 범위 설정을 업데이트하는 데 실패했습니다. 다시 시도해주세요.',
    BLOCK_FAILED: '차단에 실패했습니다. 다시 시도해주세요.',
    UNBLOCK_FAILED: '차단 해제에 실패했습니다. 다시 시도해주세요.',
    BLOCKED_USER_LIST_FETCH_FAILED: '차단 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    BLOCK_STATUS_FETCH_FAILED: '차단 상태를 불러오는 데 실패했습니다. 다시 시도해주세요.',
  },
  CLUB: {
    LEAVE_CLUB_FAILED: '동아리 탈퇴에 실패했습니다. 다시 시도해주세요.',
    INFO_FETCH_FAILED: '동아리 정보를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    MEMBERS_FETCH_FAILED: '동아리 멤버 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    MEMBER_FETCH_FAILED: '동아리 멤버를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    COUNT_FETCH_FAILED: '동아리 수를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    LIST_FETCH_FAILED: '동아리 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    RECOMMEND_FETCH_FAILED: '동아리 추천을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    JOIN_STATUS_FETCH_FAILED: '동아리 가입 상태 확인을 실패했습니다. 다시 시도해주세요.',
    INVITE_CODE_FETCH_FAILED: '초대 코드를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    INVITE_LINK_CREATE_FAILED: '초대 링크 발급에 실패했습니다. 다시 시도해주세요.',
    INVITE_LINK_DELETE_FAILED: '초대 링크 삭제에 실패했습니다. 다시 시도해주세요.',
    CREATE_FAILED: '동아리 개설에 실패했습니다. 다시 시도해주세요.',
    EDIT_FAILED: '동아리 정보 수정에 실패했습니다. 다시 시도해주세요.',
    JOIN_FAILED: '동아리 가입에 실패했습니다. 다시 시도해주세요.',
    APPLY_FETCH_FAILED: '동아리 가입 신청을 불러오는데 실패했습니다. 다시 시도해주세요.',
    APPLY_FAILED: '동아리 가입 신청에 실패했습니다. 다시 시도해주세요.',
    CANCEL_APPLICATION_FAILED: '동아리 가입 신청 취소에 실패했습니다. 다시 시도해주세요.',
    APPROVE_FAILED: '동아리 가입 승인에 실패했습니다. 다시 시도해주세요.',
    REJECTED_FAILED: '동아리 가입 거절에 실패했습니다. 다시 시도해주세요.',
    CHANGE_MEMBER_ROLE_FAILED: '역할 변경에 실패했습니다. 다시 시도해주세요',
    EXPEL_MEMBER_FAILED: '멤버 추방에 실패했습니다. 다시 시도해주세요',
    WRITE_INQUIRY_FAILED: '문의 작성에 실패했습니다. 다시 시도해주세요',
    DELETE_INQUIRY_FAILED: '문의 삭제에 실패했습니다. 다시 시도해주세요',
    FETCH_INQUIRY_FAILED: '문의를 불러오는 데 실패했습니다. 다시 시도해주세요',
    FETCH_ANNOUNCEMENTS_FAILED: '공지 목록를 불러오는 데 실패했습니다. 다시 시도해주세요',
    FETCH_ANNOUNCEMENT_FAILED: '공지를 불러오는 데 실패했습니다. 다시 시도해주세요',
    WRITE_ANNOUNCEMENT_FAILED: '공지 작성에 실패했습니다. 다시 시도해주세요',
    DELETE_ANNOUNCEMENT_FAILED: '공지 삭제에 실패했습니다. 다시 시도해주세요',
    EDIT_ANNOUNCEMENT_FAILED: '공지 수정에 실패했습니다. 다시 시도해주세요',
    NICKNAME_FETCH_FAILED: '동아리 활동명을 불러오는 데 실패했습니다. 다시 시도해주세요',
    UPDATE_NICKNAME_FAILED: '동아리 활동명 변경에 실패했습니다. 다시 시도해주세요',
  },
  UNIVERSITY: {
    LIST_FETCH_FAILED: '대학 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
  },
  FEED: {
    DETAIL_FETCH_FAILED: '피드 정보를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    LIST_FETCH_FAILED: '피드 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    WRITE_FAILED: '피드 작성에 실패했습니다. 다시 시도해주세요.',
    EDIT_FAILED: '피드 수정에 실패했습니다. 다시 시도해주세요.',
    DELETE_FAILED: '피드 삭제에 실패했습니다. 다시 시도해주세요.',
    AUTHOR_CHECK_FAILED: '내 글인지 확인을 실패했습니다. 다시 시도해주세요.',
  },
  HASHTAG: {
    FETCH_FAILED: '해시태그를 불러오는 데 실패했습니다. 다시 시도해주세요.',
  },
  COMMENT: {
    FETCH_FAILED: '댓글을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    COUNT_FETCH_FAILED: '댓글 수를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    LIST_FETCH_FAILED: '댓글 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
    WRITE_FAILED: '댓글 작성에 실패했습니다. 다시 시도해주세요.',
    DELETE_FAILED: '댓글 삭제에 실패했습니다. 다시 시도해주세요.',
  },
  IMAGE: {
    LOGO_UPLOAD_FAILED: '로고 업로드에 실패했습니다. 다시 시도해주세요.',
    BACKGROUND_UPLOAD_FAILED: '배경 사진 업로드에 실패했습니다. 다시 시도해주세요.',
    PHOTO_UPLOAD_FAILED: '사진 업로드에 실패했습니다. 다시 시도해주세요.',
    AVATAR_UPLOAD_FAILED: '프로필 사진 업로드에 실패했습니다. 다시 시도해주세요.',
  },
  LIKE: {
    USERS_FETCH_FAILED: '좋아요 유저 리스트를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    COUNT_FETCH_FAILED: '좋아요 수를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    MY_LIKE_FETCH_FAILED: '내 좋아요 여부를 불러오는 데 실패했습니다. 다시 시도해주세요.',
    TOGGLE_FAILED: '좋아요 추가/삭제에 실패했습니다. 다시 시도해주세요.',
  },
  FEEDBACK: {
    SEND_FAILED: '피드백 전송에 실패했습니다. 다시 시도해주세요.',
  },
  CHATS: {
    FETCH_FAILED: '채팅방 목록을 불러오는 데 실패했습니다. 다시 시도해주세요.',
  },
};

const SPORTS_CATEGORIES = [
  '축구',
  '농구',
  '야구',
  '탁구',
  '배구',
  '볼링',
  '수영',
  '런닝',
  '등산',
  '테니스',
  '자전거',
  '유도',
  '주짓수',
  '태권도',
  '복싱',
  '스키',
  '보드',
  '서핑',
  '배드민턴',
  '클라이밍',
  '기타운동',
];

const ART_CATEGORIES = [
  '밴드',
  '댄스',
  '연극',
  '뮤지컬',
  '합창',
  '악기',
  '국악',
  '작곡',
  '응원단',
  '드로잉',
  '공예',
  '만화',
  '영상제작',
  '마술',
  '기타예술',
];

const HOBBY_CATEGORIES = [
  '게임',
  '독서',
  '영화',
  '사진',
  '여행',
  '요리',
  '보드게임',
  '맛집탐방',
  '주류',
  '경기직관',
  '전시관람',
  '기타취미',
];

const SOCIETY_CATEGORIES = ['봉사', '종교', '기타사회'];

const ACADEMIC_CATEGORIES = [
  '인문',
  '경제',
  '금융',
  '법',
  '공학',
  '자연과학',
  '수학',
  '환경',
  '창업',
  '주식',
  '회화',
  '토론',
  '의학',
  'IT',
  '기타학술',
];

export { SPORTS_CATEGORIES, ART_CATEGORIES, HOBBY_CATEGORIES, SOCIETY_CATEGORIES, ACADEMIC_CATEGORIES, ERROR_MESSAGE };
